### ISSUE TITLE
フォルダ分け機能実装

### ISSUE THREAD

**Issue by ghost** [camp-team/Encounter-Management#73]
## Todo
- [ ] フォルダ分け(Create)機能実装 #88
- [ ] フォルダ分け(Read)機能実装 #89
- [ ] フォルダ分け(Update)機能実装 #90
- [ ] フォルダ分け(Delete)機能実装 #91

## やりたいこと
- フォルダのCRUD

##  参考
[Drag and Drop](https://jp.infragistics.com/products/ignite-ui-angular/angular/components/drag_drop.html)
