### ISSUE TITLE
タスクマップ

### ISSUE THREAD

**Issue by ghost** [camp-team/Encounter-Management#79]
## 画面
- [x] 特定商取引法に基づく表記のページの実装 #13 
- [x] 利用規約のページの実装 #39 
- [x] Welcome画面実装 #48 
- [x] Footerページの実装 #41
- [x] ヘッダー画面の作成 #51 
- [x] リスト一覧画面の作成 #18 
- [x] リスト詳細ページの作成 #19
- [x] 404ページの実装 #70
- [x] プライバシーポリシー #83 
- [x] Shell画面の作成 #101 
- [ ] 検索画面のマークアップ #115
- [ ] デアカンについて #99
- [ ] 設定画面実装 #72
- [ ] アカウント管理画面の実装 #71
- [ ] 決済履歴画面実装 #67
- [ ] クレジット画面の作成 #22
## 機能
- [x] ログイン・ログアウト機能の実装 #60 
- [ ] 画像アップロード機能実装 #93 
- [x] 友達情報CRUD機能実装 #69
- [x] 友達情報の新規作成機能実装(Create) #102
- [x] 友達情報の新規作成画面表示機能実装(Read) #104
- [x] 友達情報の編集画面表示機能実装(Read) #105
- [x] 友達情報の一覧画面表示機能実装(Read) #106
- [x] 友達情報の削除機能実装(Delete) #107
- [ ] フォルダ分け機能実装 #73
- [ ] フォルダ分け(Create)機能実装 #88
- [ ] フォルダ分け(Read)機能実装 #89
- [ ] フォルダ分け(Update)機能実装 #90
- [ ] フォルダ分け(Delete)機能実装 #91
- [ ] Algolia設計 #68
- [ ] 検索機能実装 #80 
- [ ] メール通知機能実装 #66
- [ ] 課金機能実装 #20 
- [ ] Twitterログイン機能実装 #82
- [ ] PWA対応 #85
## 実装未定
- [ ] Drag and Drop機能 #113
- [ ] Tabs機能 #114
- [ ] LINEログイン機能 #116
